package com.pfms.dal.mybatis.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class FormVmExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pfmsvm_form
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pfmsvm_form
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pfmsvm_form
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsvm_form
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    public FormVmExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsvm_form
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsvm_form
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsvm_form
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsvm_form
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsvm_form
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsvm_form
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsvm_form
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsvm_form
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsvm_form
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsvm_form
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pfmsvm_form
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andTypeIsNull() {
            addCriterion("TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("TYPE =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("TYPE <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("TYPE >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TYPE >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("TYPE <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("TYPE <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("TYPE like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("TYPE not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("TYPE in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("TYPE not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("TYPE between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("TYPE not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andValueDateIsNull() {
            addCriterion("VALUE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andValueDateIsNotNull() {
            addCriterion("VALUE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andValueDateEqualTo(Date value) {
            addCriterionForJDBCDate("VALUE_DATE =", value, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("VALUE_DATE <>", value, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateGreaterThan(Date value) {
            addCriterionForJDBCDate("VALUE_DATE >", value, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("VALUE_DATE >=", value, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateLessThan(Date value) {
            addCriterionForJDBCDate("VALUE_DATE <", value, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("VALUE_DATE <=", value, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateIn(List<Date> values) {
            addCriterionForJDBCDate("VALUE_DATE in", values, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("VALUE_DATE not in", values, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("VALUE_DATE between", value1, value2, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("VALUE_DATE not between", value1, value2, "valueDate");
            return (Criteria) this;
        }

        public Criteria andTimeNoIsNull() {
            addCriterion("TIME_NO is null");
            return (Criteria) this;
        }

        public Criteria andTimeNoIsNotNull() {
            addCriterion("TIME_NO is not null");
            return (Criteria) this;
        }

        public Criteria andTimeNoEqualTo(String value) {
            addCriterion("TIME_NO =", value, "timeNo");
            return (Criteria) this;
        }

        public Criteria andTimeNoNotEqualTo(String value) {
            addCriterion("TIME_NO <>", value, "timeNo");
            return (Criteria) this;
        }

        public Criteria andTimeNoGreaterThan(String value) {
            addCriterion("TIME_NO >", value, "timeNo");
            return (Criteria) this;
        }

        public Criteria andTimeNoGreaterThanOrEqualTo(String value) {
            addCriterion("TIME_NO >=", value, "timeNo");
            return (Criteria) this;
        }

        public Criteria andTimeNoLessThan(String value) {
            addCriterion("TIME_NO <", value, "timeNo");
            return (Criteria) this;
        }

        public Criteria andTimeNoLessThanOrEqualTo(String value) {
            addCriterion("TIME_NO <=", value, "timeNo");
            return (Criteria) this;
        }

        public Criteria andTimeNoLike(String value) {
            addCriterion("TIME_NO like", value, "timeNo");
            return (Criteria) this;
        }

        public Criteria andTimeNoNotLike(String value) {
            addCriterion("TIME_NO not like", value, "timeNo");
            return (Criteria) this;
        }

        public Criteria andTimeNoIn(List<String> values) {
            addCriterion("TIME_NO in", values, "timeNo");
            return (Criteria) this;
        }

        public Criteria andTimeNoNotIn(List<String> values) {
            addCriterion("TIME_NO not in", values, "timeNo");
            return (Criteria) this;
        }

        public Criteria andTimeNoBetween(String value1, String value2) {
            addCriterion("TIME_NO between", value1, value2, "timeNo");
            return (Criteria) this;
        }

        public Criteria andTimeNoNotBetween(String value1, String value2) {
            addCriterion("TIME_NO not between", value1, value2, "timeNo");
            return (Criteria) this;
        }

        public Criteria andAmountIsNull() {
            addCriterion("AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andAmountIsNotNull() {
            addCriterion("AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andAmountEqualTo(BigDecimal value) {
            addCriterion("AMOUNT =", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotEqualTo(BigDecimal value) {
            addCriterion("AMOUNT <>", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThan(BigDecimal value) {
            addCriterion("AMOUNT >", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AMOUNT >=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThan(BigDecimal value) {
            addCriterion("AMOUNT <", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AMOUNT <=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountIn(List<BigDecimal> values) {
            addCriterion("AMOUNT in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotIn(List<BigDecimal> values) {
            addCriterion("AMOUNT not in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AMOUNT between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AMOUNT not between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andUsageLevelOneIsNull() {
            addCriterion("USAGE_LEVEL_ONE is null");
            return (Criteria) this;
        }

        public Criteria andUsageLevelOneIsNotNull() {
            addCriterion("USAGE_LEVEL_ONE is not null");
            return (Criteria) this;
        }

        public Criteria andUsageLevelOneEqualTo(String value) {
            addCriterion("USAGE_LEVEL_ONE =", value, "usageLevelOne");
            return (Criteria) this;
        }

        public Criteria andUsageLevelOneNotEqualTo(String value) {
            addCriterion("USAGE_LEVEL_ONE <>", value, "usageLevelOne");
            return (Criteria) this;
        }

        public Criteria andUsageLevelOneGreaterThan(String value) {
            addCriterion("USAGE_LEVEL_ONE >", value, "usageLevelOne");
            return (Criteria) this;
        }

        public Criteria andUsageLevelOneGreaterThanOrEqualTo(String value) {
            addCriterion("USAGE_LEVEL_ONE >=", value, "usageLevelOne");
            return (Criteria) this;
        }

        public Criteria andUsageLevelOneLessThan(String value) {
            addCriterion("USAGE_LEVEL_ONE <", value, "usageLevelOne");
            return (Criteria) this;
        }

        public Criteria andUsageLevelOneLessThanOrEqualTo(String value) {
            addCriterion("USAGE_LEVEL_ONE <=", value, "usageLevelOne");
            return (Criteria) this;
        }

        public Criteria andUsageLevelOneLike(String value) {
            addCriterion("USAGE_LEVEL_ONE like", value, "usageLevelOne");
            return (Criteria) this;
        }

        public Criteria andUsageLevelOneNotLike(String value) {
            addCriterion("USAGE_LEVEL_ONE not like", value, "usageLevelOne");
            return (Criteria) this;
        }

        public Criteria andUsageLevelOneIn(List<String> values) {
            addCriterion("USAGE_LEVEL_ONE in", values, "usageLevelOne");
            return (Criteria) this;
        }

        public Criteria andUsageLevelOneNotIn(List<String> values) {
            addCriterion("USAGE_LEVEL_ONE not in", values, "usageLevelOne");
            return (Criteria) this;
        }

        public Criteria andUsageLevelOneBetween(String value1, String value2) {
            addCriterion("USAGE_LEVEL_ONE between", value1, value2, "usageLevelOne");
            return (Criteria) this;
        }

        public Criteria andUsageLevelOneNotBetween(String value1, String value2) {
            addCriterion("USAGE_LEVEL_ONE not between", value1, value2, "usageLevelOne");
            return (Criteria) this;
        }

        public Criteria andUsageLevelOneNameIsNull() {
            addCriterion("USAGE_LEVEL_ONE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andUsageLevelOneNameIsNotNull() {
            addCriterion("USAGE_LEVEL_ONE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andUsageLevelOneNameEqualTo(String value) {
            addCriterion("USAGE_LEVEL_ONE_NAME =", value, "usageLevelOneName");
            return (Criteria) this;
        }

        public Criteria andUsageLevelOneNameNotEqualTo(String value) {
            addCriterion("USAGE_LEVEL_ONE_NAME <>", value, "usageLevelOneName");
            return (Criteria) this;
        }

        public Criteria andUsageLevelOneNameGreaterThan(String value) {
            addCriterion("USAGE_LEVEL_ONE_NAME >", value, "usageLevelOneName");
            return (Criteria) this;
        }

        public Criteria andUsageLevelOneNameGreaterThanOrEqualTo(String value) {
            addCriterion("USAGE_LEVEL_ONE_NAME >=", value, "usageLevelOneName");
            return (Criteria) this;
        }

        public Criteria andUsageLevelOneNameLessThan(String value) {
            addCriterion("USAGE_LEVEL_ONE_NAME <", value, "usageLevelOneName");
            return (Criteria) this;
        }

        public Criteria andUsageLevelOneNameLessThanOrEqualTo(String value) {
            addCriterion("USAGE_LEVEL_ONE_NAME <=", value, "usageLevelOneName");
            return (Criteria) this;
        }

        public Criteria andUsageLevelOneNameLike(String value) {
            addCriterion("USAGE_LEVEL_ONE_NAME like", value, "usageLevelOneName");
            return (Criteria) this;
        }

        public Criteria andUsageLevelOneNameNotLike(String value) {
            addCriterion("USAGE_LEVEL_ONE_NAME not like", value, "usageLevelOneName");
            return (Criteria) this;
        }

        public Criteria andUsageLevelOneNameIn(List<String> values) {
            addCriterion("USAGE_LEVEL_ONE_NAME in", values, "usageLevelOneName");
            return (Criteria) this;
        }

        public Criteria andUsageLevelOneNameNotIn(List<String> values) {
            addCriterion("USAGE_LEVEL_ONE_NAME not in", values, "usageLevelOneName");
            return (Criteria) this;
        }

        public Criteria andUsageLevelOneNameBetween(String value1, String value2) {
            addCriterion("USAGE_LEVEL_ONE_NAME between", value1, value2, "usageLevelOneName");
            return (Criteria) this;
        }

        public Criteria andUsageLevelOneNameNotBetween(String value1, String value2) {
            addCriterion("USAGE_LEVEL_ONE_NAME not between", value1, value2, "usageLevelOneName");
            return (Criteria) this;
        }

        public Criteria andUsageLevelTwoIsNull() {
            addCriterion("USAGE_LEVEL_TWO is null");
            return (Criteria) this;
        }

        public Criteria andUsageLevelTwoIsNotNull() {
            addCriterion("USAGE_LEVEL_TWO is not null");
            return (Criteria) this;
        }

        public Criteria andUsageLevelTwoEqualTo(String value) {
            addCriterion("USAGE_LEVEL_TWO =", value, "usageLevelTwo");
            return (Criteria) this;
        }

        public Criteria andUsageLevelTwoNotEqualTo(String value) {
            addCriterion("USAGE_LEVEL_TWO <>", value, "usageLevelTwo");
            return (Criteria) this;
        }

        public Criteria andUsageLevelTwoGreaterThan(String value) {
            addCriterion("USAGE_LEVEL_TWO >", value, "usageLevelTwo");
            return (Criteria) this;
        }

        public Criteria andUsageLevelTwoGreaterThanOrEqualTo(String value) {
            addCriterion("USAGE_LEVEL_TWO >=", value, "usageLevelTwo");
            return (Criteria) this;
        }

        public Criteria andUsageLevelTwoLessThan(String value) {
            addCriterion("USAGE_LEVEL_TWO <", value, "usageLevelTwo");
            return (Criteria) this;
        }

        public Criteria andUsageLevelTwoLessThanOrEqualTo(String value) {
            addCriterion("USAGE_LEVEL_TWO <=", value, "usageLevelTwo");
            return (Criteria) this;
        }

        public Criteria andUsageLevelTwoLike(String value) {
            addCriterion("USAGE_LEVEL_TWO like", value, "usageLevelTwo");
            return (Criteria) this;
        }

        public Criteria andUsageLevelTwoNotLike(String value) {
            addCriterion("USAGE_LEVEL_TWO not like", value, "usageLevelTwo");
            return (Criteria) this;
        }

        public Criteria andUsageLevelTwoIn(List<String> values) {
            addCriterion("USAGE_LEVEL_TWO in", values, "usageLevelTwo");
            return (Criteria) this;
        }

        public Criteria andUsageLevelTwoNotIn(List<String> values) {
            addCriterion("USAGE_LEVEL_TWO not in", values, "usageLevelTwo");
            return (Criteria) this;
        }

        public Criteria andUsageLevelTwoBetween(String value1, String value2) {
            addCriterion("USAGE_LEVEL_TWO between", value1, value2, "usageLevelTwo");
            return (Criteria) this;
        }

        public Criteria andUsageLevelTwoNotBetween(String value1, String value2) {
            addCriterion("USAGE_LEVEL_TWO not between", value1, value2, "usageLevelTwo");
            return (Criteria) this;
        }

        public Criteria andUsageLevelTwoNameIsNull() {
            addCriterion("USAGE_LEVEL_TWO_NAME is null");
            return (Criteria) this;
        }

        public Criteria andUsageLevelTwoNameIsNotNull() {
            addCriterion("USAGE_LEVEL_TWO_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andUsageLevelTwoNameEqualTo(String value) {
            addCriterion("USAGE_LEVEL_TWO_NAME =", value, "usageLevelTwoName");
            return (Criteria) this;
        }

        public Criteria andUsageLevelTwoNameNotEqualTo(String value) {
            addCriterion("USAGE_LEVEL_TWO_NAME <>", value, "usageLevelTwoName");
            return (Criteria) this;
        }

        public Criteria andUsageLevelTwoNameGreaterThan(String value) {
            addCriterion("USAGE_LEVEL_TWO_NAME >", value, "usageLevelTwoName");
            return (Criteria) this;
        }

        public Criteria andUsageLevelTwoNameGreaterThanOrEqualTo(String value) {
            addCriterion("USAGE_LEVEL_TWO_NAME >=", value, "usageLevelTwoName");
            return (Criteria) this;
        }

        public Criteria andUsageLevelTwoNameLessThan(String value) {
            addCriterion("USAGE_LEVEL_TWO_NAME <", value, "usageLevelTwoName");
            return (Criteria) this;
        }

        public Criteria andUsageLevelTwoNameLessThanOrEqualTo(String value) {
            addCriterion("USAGE_LEVEL_TWO_NAME <=", value, "usageLevelTwoName");
            return (Criteria) this;
        }

        public Criteria andUsageLevelTwoNameLike(String value) {
            addCriterion("USAGE_LEVEL_TWO_NAME like", value, "usageLevelTwoName");
            return (Criteria) this;
        }

        public Criteria andUsageLevelTwoNameNotLike(String value) {
            addCriterion("USAGE_LEVEL_TWO_NAME not like", value, "usageLevelTwoName");
            return (Criteria) this;
        }

        public Criteria andUsageLevelTwoNameIn(List<String> values) {
            addCriterion("USAGE_LEVEL_TWO_NAME in", values, "usageLevelTwoName");
            return (Criteria) this;
        }

        public Criteria andUsageLevelTwoNameNotIn(List<String> values) {
            addCriterion("USAGE_LEVEL_TWO_NAME not in", values, "usageLevelTwoName");
            return (Criteria) this;
        }

        public Criteria andUsageLevelTwoNameBetween(String value1, String value2) {
            addCriterion("USAGE_LEVEL_TWO_NAME between", value1, value2, "usageLevelTwoName");
            return (Criteria) this;
        }

        public Criteria andUsageLevelTwoNameNotBetween(String value1, String value2) {
            addCriterion("USAGE_LEVEL_TWO_NAME not between", value1, value2, "usageLevelTwoName");
            return (Criteria) this;
        }

        public Criteria andCreatorIdIsNull() {
            addCriterion("CREATOR_ID is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIdIsNotNull() {
            addCriterion("CREATOR_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorIdEqualTo(Integer value) {
            addCriterion("CREATOR_ID =", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdNotEqualTo(Integer value) {
            addCriterion("CREATOR_ID <>", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdGreaterThan(Integer value) {
            addCriterion("CREATOR_ID >", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("CREATOR_ID >=", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdLessThan(Integer value) {
            addCriterion("CREATOR_ID <", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdLessThanOrEqualTo(Integer value) {
            addCriterion("CREATOR_ID <=", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdIn(List<Integer> values) {
            addCriterion("CREATOR_ID in", values, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdNotIn(List<Integer> values) {
            addCriterion("CREATOR_ID not in", values, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdBetween(Integer value1, Integer value2) {
            addCriterion("CREATOR_ID between", value1, value2, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdNotBetween(Integer value1, Integer value2) {
            addCriterion("CREATOR_ID not between", value1, value2, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifierIdIsNull() {
            addCriterion("MODIFIER_ID is null");
            return (Criteria) this;
        }

        public Criteria andModifierIdIsNotNull() {
            addCriterion("MODIFIER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andModifierIdEqualTo(Integer value) {
            addCriterion("MODIFIER_ID =", value, "modifierId");
            return (Criteria) this;
        }

        public Criteria andModifierIdNotEqualTo(Integer value) {
            addCriterion("MODIFIER_ID <>", value, "modifierId");
            return (Criteria) this;
        }

        public Criteria andModifierIdGreaterThan(Integer value) {
            addCriterion("MODIFIER_ID >", value, "modifierId");
            return (Criteria) this;
        }

        public Criteria andModifierIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("MODIFIER_ID >=", value, "modifierId");
            return (Criteria) this;
        }

        public Criteria andModifierIdLessThan(Integer value) {
            addCriterion("MODIFIER_ID <", value, "modifierId");
            return (Criteria) this;
        }

        public Criteria andModifierIdLessThanOrEqualTo(Integer value) {
            addCriterion("MODIFIER_ID <=", value, "modifierId");
            return (Criteria) this;
        }

        public Criteria andModifierIdIn(List<Integer> values) {
            addCriterion("MODIFIER_ID in", values, "modifierId");
            return (Criteria) this;
        }

        public Criteria andModifierIdNotIn(List<Integer> values) {
            addCriterion("MODIFIER_ID not in", values, "modifierId");
            return (Criteria) this;
        }

        public Criteria andModifierIdBetween(Integer value1, Integer value2) {
            addCriterion("MODIFIER_ID between", value1, value2, "modifierId");
            return (Criteria) this;
        }

        public Criteria andModifierIdNotBetween(Integer value1, Integer value2) {
            addCriterion("MODIFIER_ID not between", value1, value2, "modifierId");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("MODIFY_TIME is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("MODIFY_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("MODIFY_TIME =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("MODIFY_TIME <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("MODIFY_TIME >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFY_TIME >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("MODIFY_TIME <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("MODIFY_TIME <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("MODIFY_TIME in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("MODIFY_TIME not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("MODIFY_TIME between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("MODIFY_TIME not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pfmsvm_form
     *
     * @mbggenerated do_not_delete_during_merge Wed Jul 06 14:40:25 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pfmsvm_form
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}