package com.pfms.dal.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class PfmsUsageLevelTwo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_usage_level_two.ID
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_usage_level_two.TYPE
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_usage_level_two.FATHER_ID
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    private String fatherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_usage_level_two.NAME
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_usage_level_two.CREATOR_ID
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    private Integer creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_usage_level_two.CREATE_TIME
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_usage_level_two.DESCRIPT
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    private String descript;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_usage_level_two.MONTHBUDGET
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    private BigDecimal monthbudget;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_usage_level_two.ID
     *
     * @return the value of pfmsdb_usage_level_two.ID
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_usage_level_two.ID
     *
     * @param id the value for pfmsdb_usage_level_two.ID
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_usage_level_two.TYPE
     *
     * @return the value of pfmsdb_usage_level_two.TYPE
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_usage_level_two.TYPE
     *
     * @param type the value for pfmsdb_usage_level_two.TYPE
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_usage_level_two.FATHER_ID
     *
     * @return the value of pfmsdb_usage_level_two.FATHER_ID
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    public String getFatherId() {
        return fatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_usage_level_two.FATHER_ID
     *
     * @param fatherId the value for pfmsdb_usage_level_two.FATHER_ID
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    public void setFatherId(String fatherId) {
        this.fatherId = fatherId == null ? null : fatherId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_usage_level_two.NAME
     *
     * @return the value of pfmsdb_usage_level_two.NAME
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_usage_level_two.NAME
     *
     * @param name the value for pfmsdb_usage_level_two.NAME
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_usage_level_two.CREATOR_ID
     *
     * @return the value of pfmsdb_usage_level_two.CREATOR_ID
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_usage_level_two.CREATOR_ID
     *
     * @param creatorId the value for pfmsdb_usage_level_two.CREATOR_ID
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_usage_level_two.CREATE_TIME
     *
     * @return the value of pfmsdb_usage_level_two.CREATE_TIME
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_usage_level_two.CREATE_TIME
     *
     * @param createTime the value for pfmsdb_usage_level_two.CREATE_TIME
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_usage_level_two.DESCRIPT
     *
     * @return the value of pfmsdb_usage_level_two.DESCRIPT
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    public String getDescript() {
        return descript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_usage_level_two.DESCRIPT
     *
     * @param descript the value for pfmsdb_usage_level_two.DESCRIPT
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    public void setDescript(String descript) {
        this.descript = descript == null ? null : descript.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_usage_level_two.MONTHBUDGET
     *
     * @return the value of pfmsdb_usage_level_two.MONTHBUDGET
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    public BigDecimal getMonthbudget() {
        return monthbudget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_usage_level_two.MONTHBUDGET
     *
     * @param monthbudget the value for pfmsdb_usage_level_two.MONTHBUDGET
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    public void setMonthbudget(BigDecimal monthbudget) {
        this.monthbudget = monthbudget;
    }
}