package com.pfms.dal.mybatis.model;

import java.math.BigDecimal;

public class RealStatistics extends RealStatisticsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_realstatistics.BUDGET
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    private BigDecimal budget;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_realstatistics.REALAMOUNT
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    private BigDecimal realamount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_realstatistics.BUDGET
     *
     * @return the value of pfmsdb_realstatistics.BUDGET
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    public BigDecimal getBudget() {
        return budget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_realstatistics.BUDGET
     *
     * @param budget the value for pfmsdb_realstatistics.BUDGET
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    public void setBudget(BigDecimal budget) {
        this.budget = budget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_realstatistics.REALAMOUNT
     *
     * @return the value of pfmsdb_realstatistics.REALAMOUNT
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    public BigDecimal getRealamount() {
        return realamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_realstatistics.REALAMOUNT
     *
     * @param realamount the value for pfmsdb_realstatistics.REALAMOUNT
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    public void setRealamount(BigDecimal realamount) {
        this.realamount = realamount;
    }
}