package com.pfms.dal.mybatis.model;

public class RealStatisticsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_realstatistics.ID
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_realstatistics.MONTH
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    private String month;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_realstatistics.ID
     *
     * @return the value of pfmsdb_realstatistics.ID
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_realstatistics.ID
     *
     * @param id the value for pfmsdb_realstatistics.ID
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_realstatistics.MONTH
     *
     * @return the value of pfmsdb_realstatistics.MONTH
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_realstatistics.MONTH
     *
     * @param month the value for pfmsdb_realstatistics.MONTH
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    public void setMonth(String month) {
        this.month = month == null ? null : month.trim();
    }
}