package com.pfms.dal.mybatis.dao;

import com.pfms.dal.mybatis.model.FormVm;
import com.pfms.dal.mybatis.model.FormVmExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FormVmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsvm_form
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    int countByExample(FormVmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsvm_form
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    int deleteByExample(FormVmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsvm_form
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    int insert(FormVm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsvm_form
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    int insertSelective(FormVm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsvm_form
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    List<FormVm> selectByExample(FormVmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsvm_form
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    int updateByExampleSelective(@Param("record") FormVm record, @Param("example") FormVmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsvm_form
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    int updateByExample(@Param("record") FormVm record, @Param("example") FormVmExample example);
}