package com.pfms.dal.mybatis.dao;

import com.pfms.dal.mybatis.model.PfmsUsageLevelTwo;
import com.pfms.dal.mybatis.model.PfmsUsageLevelTwoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PfmsUsageLevelTwoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_usage_level_two
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    int countByExample(PfmsUsageLevelTwoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_usage_level_two
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    int deleteByExample(PfmsUsageLevelTwoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_usage_level_two
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_usage_level_two
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    int insert(PfmsUsageLevelTwo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_usage_level_two
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    int insertSelective(PfmsUsageLevelTwo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_usage_level_two
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    List<PfmsUsageLevelTwo> selectByExample(PfmsUsageLevelTwoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_usage_level_two
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    PfmsUsageLevelTwo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_usage_level_two
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    int updateByExampleSelective(@Param("record") PfmsUsageLevelTwo record, @Param("example") PfmsUsageLevelTwoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_usage_level_two
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    int updateByExample(@Param("record") PfmsUsageLevelTwo record, @Param("example") PfmsUsageLevelTwoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_usage_level_two
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    int updateByPrimaryKeySelective(PfmsUsageLevelTwo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_usage_level_two
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    int updateByPrimaryKey(PfmsUsageLevelTwo record);
}