package com.pfms.dal.mybatis.dao;

import com.pfms.dal.mybatis.model.PfmsUsageLevelOne;
import com.pfms.dal.mybatis.model.PfmsUsageLevelOneExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PfmsUsageLevelOneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_usage_level_one
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    int countByExample(PfmsUsageLevelOneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_usage_level_one
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    int deleteByExample(PfmsUsageLevelOneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_usage_level_one
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_usage_level_one
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    int insert(PfmsUsageLevelOne record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_usage_level_one
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    int insertSelective(PfmsUsageLevelOne record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_usage_level_one
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    List<PfmsUsageLevelOne> selectByExample(PfmsUsageLevelOneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_usage_level_one
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    PfmsUsageLevelOne selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_usage_level_one
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    int updateByExampleSelective(@Param("record") PfmsUsageLevelOne record, @Param("example") PfmsUsageLevelOneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_usage_level_one
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    int updateByExample(@Param("record") PfmsUsageLevelOne record, @Param("example") PfmsUsageLevelOneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_usage_level_one
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    int updateByPrimaryKeySelective(PfmsUsageLevelOne record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_usage_level_one
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    int updateByPrimaryKey(PfmsUsageLevelOne record);
}