package com.pfms.dal.mybatis.dao;

import com.pfms.dal.mybatis.model.Sequence;
import com.pfms.dal.mybatis.model.SequenceExample;
import com.pfms.dal.mybatis.model.SequenceKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SequenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    int countByExample(SequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    int deleteByExample(SequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    int deleteByPrimaryKey(SequenceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    int insert(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    int insertSelective(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    List<Sequence> selectByExample(SequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    Sequence selectByPrimaryKey(SequenceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    int updateByExampleSelective(@Param("record") Sequence record, @Param("example") SequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    int updateByExample(@Param("record") Sequence record, @Param("example") SequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    int updateByPrimaryKeySelective(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbggenerated Wed Jul 06 14:40:25 CST 2016
     */
    int updateByPrimaryKey(Sequence record);
}